### ISSUE TITLE
Multiple errors in logs for statistics plugin

### ISSUE THREAD

**Issue by macin** [cosmocode/dokuwiki-plugin-statistics#78]
Hi, 
Not sure when it started, but it's been like this for  while now, the statistics plugin is generating a lot of following error logs, for every page view. This is on Kaos 6a...
Any hints as to what coudl be causing this? I have reinstalled the plugin but that did not help.
@splitbrain  fyi

```
2024-11-25 23:35:34
E_WARNING: Undefined property: stdClass::$Crawler
/var/www/html/lib/plugins/statistics/inc/StatisticsLogger.class.php(27)
#0 /var/www/html/lib/plugins/statistics/inc/StatisticsLogger.class.php(27): dokuwiki\ErrorHandler::errorHandler(2, '...', '...', 27)
#1 /var/www/html/lib/plugins/statistics/helper.php(46): StatisticsLogger->__construct(Object(helper_plugin_statistics))
#2 /var/www/html/lib/plugins/statistics/log.php(32): helper_plugin_statistics->Logger()
#3 {main}
2024-11-25 23:35:34
E_WARNING: Undefined property: stdClass::$isSyndicationReader
/var/www/html/lib/plugins/statistics/inc/StatisticsLogger.class.php(28)
#0 /var/www/html/lib/plugins/statistics/inc/StatisticsLogger.class.php(28): dokuwiki\ErrorHandler::errorHandler(2, '...', '...', 28)
#1 /var/www/html/lib/plugins/statistics/helper.php(46): StatisticsLogger->__construct(Object(helper_plugin_statistics))
#2 /var/www/html/lib/plugins/statistics/log.php(32): helper_plugin_statistics->Logger()
#3 {main}
2024-11-25 23:35:34
E_WARNING: Undefined property: stdClass::$Crawler
/var/www/html/lib/plugins/statistics/inc/StatisticsLogger.class.php(27)
#0 /var/www/html/lib/plugins/statistics/inc/StatisticsLogger.class.php(27): dokuwiki\ErrorHandler::errorHandler(2, '...', '...', 27)
#1 /var/www/html/lib/plugins/statistics/helper.php(46): StatisticsLogger->__construct(Object(helper_plugin_statistics))
#2 /var/www/html/lib/plugins/statistics/action.php(160): helper_plugin_statistics->Logger()
#3 /var/www/html/inc/Extension/EventHandler.php(80): action_plugin_statistics->logmedia(Object(dokuwiki\Extension\Event), Array)
#4 /var/www/html/inc/Extension/Event.php(75): dokuwiki\Extension\EventHandler->process_event(Object(dokuwiki\Extension\Event), '...')
#5 /var/www/html/lib/exe/fetch.php(73): dokuwiki\Extension\Event->advise_before()
#6 {main}
2024-11-25 23:35:34
E_WARNING: Undefined property: stdClass::$isSyndicationReader
/var/www/html/lib/plugins/statistics/inc/StatisticsLogger.class.php(28)
#0 /var/www/html/lib/plugins/statistics/inc/StatisticsLogger.class.php(28): dokuwiki\ErrorHandler::errorHandler(2, '...', '...', 28)
#1 /var/www/html/lib/plugins/statistics/helper.php(46): StatisticsLogger->__construct(Object(helper_plugin_statistics))
#2 /var/www/html/lib/plugins/statistics/action.php(160): helper_plugin_statistics->Logger()
#3 /var/www/html/inc/Extension/EventHandler.php(80): action_plugin_statistics->logmedia(Object(dokuwiki\Extension\Event), Array)
#4 /var/www/html/inc/Extension/Event.php(75): dokuwiki\Extension\EventHandler->process_event(Object(dokuwiki\Extension\Event), '...')
#5 /var/www/html/lib/exe/fetch.php(73): dokuwiki\Extension\Event->advise_before()
#6 {main}
2024-11-25 23:35:34
E_WARNING: Undefined array key "uid"
/var/www/html/lib/plugins/statistics/inc/StatisticsLogger.class.php(41)
#0 /var/www/html/lib/plugins/statistics/inc/StatisticsLogger.class.php(41): dokuwiki\ErrorHandler::errorHandler(2, '...', '...', 41)
#1 /var/www/html/lib/plugins/statistics/inc/StatisticsLogger.class.php(32): StatisticsLogger->getUID()
#2 /var/www/html/lib/plugins/statistics/helper.php(46): StatisticsLogger->__construct(Object(helper_plugin_statistics))
#3 /var/www/html/lib/plugins/statistics/action.php(160): helper_plugin_statistics->Logger()
#4 /var/www/html/inc/Extension/EventHandler.php(80): action_plugin_statistics->logmedia(Object(dokuwiki\Extension\Event), Array)
#5 /var/www/html/inc/Extension/Event.php(75): dokuwiki\Extension\EventHandler->process_event(Object(dokuwiki\Extension\Event), '...')
#6 /var/www/html/lib/exe/fetch.php(73): dokuwiki\Extension\Event->advise_before()
#7 {main}
2024-11-25 23:35:34
E_WARNING: Undefined array key "ses"
/var/www/html/lib/plugins/statistics/inc/StatisticsLogger.class.php(55)
#0 /var/www/html/lib/plugins/statistics/inc/StatisticsLogger.class.php(55): dokuwiki\ErrorHandler::errorHandler(2, '...', '...', 55)
#1 /var/www/html/lib/plugins/statistics/inc/StatisticsLogger.class.php(414): StatisticsLogger->getSession()
#2 /var/www/html/lib/plugins/statistics/action.php(160): StatisticsLogger->log_media('...', '...', 1, 9317)
#3 /var/www/html/inc/Extension/EventHandler.php(80): action_plugin_statistics->logmedia(Object(dokuwiki\Extension\Event), Array)
#4 /var/www/html/inc/Extension/Event.php(75): dokuwiki\Extension\EventHandler->process_event(Object(dokuwiki\Extension\Event), '...')
#5 /var/www/html/lib/exe/fetch.php(73): dokuwiki\Extension\Event->advise_before()
#6 {main}

```

**Comment by saschaleib** [comment]
These are not wrrors but "only" warnings, but of course should still be looked into. I get the same, BTW, just to +1 this report :-)
